### test
GET http://127.0.0.1:8847/PrintController/Test



###  纸张

GET http://127.0.0.1:8847/PrintController/getprintinfo?isUpdate=true



### 打印机配置信息

GET http://127.0.0.1:8847/PrintController/GetPrintConfigs


###  LoadAchieve

POST http://127.0.0.1:8847/PrintController/toprint 


{
    "WebPages":
    [
        {
            "Url":"http://127.0.0.1:5500/test.html",
            "PrintMode":"JsPrintRequest",
            "Name":"test"
        }
    ]
}

###
GET http://127.0.0.1:8847/PrintController/getscreeninfo