### test
GET http://127.0.0.1:8847/PrintController/Test



###  纸张

GET http://127.0.0.1:8847/PrintController/getprintinfo?isUpdate=true



### 打印机配置信息

GET http://127.0.0.1:8847/PrintController/GetPrintConfigs


### 

POST http://127.0.0.1:8847/PrintController/toprint 


{
    "WebPages":
    [
        {
            "Url":"http://bing.com",
            "PrintMode":"LoadAchieve",
            "Name":"2"
        }
    ]
}

###
GET http://127.0.0.1:8847/PrintController/getscreeninfo